{
 "title": "Lab 4 Observability",
 "tags": [
  "airflow",
  "spark",
  "loki",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Spark logs from Loki",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"spark_logs\"}"
    }
   ]
  },
  {
   "title": "spark-master status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-master\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "spark-worker status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-worker\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}